name: Building

on: [ push, pull_request ]

jobs:
  build:
    name: 'Building'
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ x64 ]

    env:
      solution_name: dxvk.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Cache packages
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget

    - name: Restore solution
      run: |
        nuget restore $env:solution_name

    - name: Build solution
      run: |
        msbuild $env:solution_name -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -m -nologo

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries (${{ matrix.configuration }})
        path: binaries/